### ISSUE TITLE
[BUG] Can't SSH with this role

### ISSUE THREAD

**Issue by Dynatrace-Adam-Gardner** [geerlingguy/ansible-role-ssh-chroot-jail#22]
I'm trying to use this role to create a chroot jail on AWS Linux.

I can login successfully with `ec2-user` but when I try to SSH (same keyfile), as `janedoe` I get:

`No supported authentication methods available (server sent: public key). Server refused our key.`

*Prerequisites*
```
$ yum list openssh*
Loaded plugins: priorities, update-motd, upgrade-helper
Installed Packages
openssh.x86_64                      7.4p1-16.71.amzn1               installed
openssh-clients.x86_64              7.4p1-16.71.amzn1               installed
openssh-server.x86_64               7.4p1-16.71.amzn1               installed
```

My playbook:

```
---
- name: Create chroot jail
  hosts: chroot
  become: yes

  vars:
  - ssh_chroot_jail_users:
      name: janedoe
      homedir: /home/janedoe
      shell: /bin/bash

  roles:
    - geerlingguy.ssh-chroot-jail
```

**Comment by Dynatrace-Adam-Gardner** [comment]
This role doesn't create the SSH keys directory or `authorized_keys` file. Solution is 2 post tasks:

```
  - name: Create SSH Directory
    file:
      path: /home/janedoe/.ssh
      state: directory

  - name: Copy SSH from ec2-user to janedoe
    copy:
      remote_src: yes
      src: /home/ec2-user/.ssh/authorized_keys
      dest: /home/janedoe/.ssh/authorized_keys
      owner: janedoe
```
