### ISSUE TITLE
Use systemd-tmpfiles to create devices on boot

### ISSUE THREAD

**Issue by cognifloyd** [geerlingguy/ansible-role-ssh-chroot-jail#26]
`mknod` does not create persistent devices. To make a chroot that will survive a reboot, we also need a task like this (template inlined into a copy task to be succinct):

```yaml
- name: Add chroot devices
  copy:
    content: |
      c {{ ssh_chroot_directory }}/dev/null 0666 root root - 1:3
      c {{ ssh_chroot_directory }}/dev/random 0666 root root - 5:0
      c {{ ssh_chroot_directory }}/dev/urandom 0666 root root - 1:5
      c {{ ssh_chroot_directory }}/dev/zero 0666 root root - 1:8
    dest: /etc/tmpfiles.d/ssh-chroot.conf
  notify: systemd-tmpfiles
```

with this handler.
```yaml
- name: systemd-tmpfiles
  become: yes
  command: "systemd-tmpfiles --create /etc/tmpfiles.d/ssh-chroot.conf"
```

These could replace the mknod task.
